version: '3.9'
services:
  express-app:
    build:
      context: .
      dockerfile: ExpressAppDevServerDockerfile
    ports:
      - "3333:3333"
      - "9229:9229"
    container_name: express-app
    volumes:
      - .:/workspace

  react-app:
    build:
      context: .
      dockerfile: ReactAppDevServerDockerfile
    ports:
      - "4200:4200"
    container_name: react-app
    depends_on:
      - express-app
    volumes:
      - .:/workspace

  reverse-proxy:
    build:
      context: .
      dockerfile: DevServerProxyDockerfile
    ports:
      - "8080:80"
    container_name: reverse-proxy